version: "3"

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/uploads:/var/www/html/wp-content/uploads
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: ls-02e56ccb10b1ad6a44e7dcf6f063d5398100a8ab.cokew61rfnye.us-east-2.rds.amazonaws.com
      WORDPRESS_DB_USER: dbmasteruser
      WORDPRESS_DB_PASSWORD: -aPa0-kLq1yMA:=k2B:^NOC{wg`edTRI
      WORDPRESS_DB_NAME: bd_prueba